# Modelling multiple linear regression model

In [677]:
import pandas as pd
df = pd.read_csv('../data/dataset_ALL.csv')
df

postalCode     price   n_rooms  living_area  equipped_kitchen  \
0       -1.059352  170000.0 -0.569677    -0.795057               1.0   
1        0.097873  219000.0  0.032106    -0.353534               1.0   
2        1.675033  219000.0 -1.171460    -0.382969               1.0   
3        1.578865  245000.0 -1.171460    -0.883362               1.0   
4       -1.081792  330000.0 -0.569677    -0.603730               1.0   
...           ...       ...       ...          ...               ...   
11466    0.745406  494000.0  0.633889     0.095348               0.0   
11467   -0.950362  495000.0  0.633889     0.191011               0.0   
11468   -0.434258  495000.0  0.633889     0.610458               1.0   
11469   -0.953567  499000.0 -1.773243     1.162361               1.0   
11470   -0.815405  499000.0  1.235672     0.845937               0.0   

       furnished  fireplace  terrace  area_terrace  garden  ...  \
0            0.0        0.0      1.0     -0.523385     0.0  ...   
1            0.0        0.0      1.0      0.101605     1.0  ...   
2            0.0        0.0      0.0     -0.589173     1.0  ...   
3            0.0        0.0      1.0     -0.260231     0.0  ...   
4            0.0        0.0      1.0     -0.326020     0.0  ...   
...          ...        ...      ...           ...     ...  ...   
11466        0.0        0.0      1.0      0.726594     1.0  ...   
11467        0.0        0.0      1.0      0.002922     0.0  ...   
11468        0.0        0.0      1.0      0.068710     1.0  ...   
11469        0.0        0.0      0.0     -0.589173     0.0  ...   
11470        0.0        0.0      1.0      0.825277     1.0  ...   

       subtype_property_LOFT  subtype_property_MANOR_HOUSE  \
0                      False                         False   
1                      False                         False   
2                      False                         False   
3                      False                         False   
4                      False                         False   
...                      ...                           ...   
11466                  False                         False   
11467                  False                         False   
11468                  False                         False   
11469                  False                         False   
11470                  False                         False   

       subtype_property_MANSION  subtype_property_MIXED_USE_BUILDING  \
0                         False                                False   
1                         False                                False   
2                         False                                False   
3                         False                                False   
4                         False                                False   
...                         ...                                  ...   
11466                      True                                False   
11467                     False                                False   
11468                     False                                False   
11469                     False                                 True   
11470                     False                                False   

       subtype_property_OTHER_PROPERTY  subtype_property_PENTHOUSE  \
0                                False                       False   
1                                False                       False   
2                                False                       False   
3                                False                       False   
4                                False                       False   
...                                ...                         ...   
11466                            False                       False   
11467                            False                       False   
11468                            False                       False   
11469                      

In [678]:
import numpy as np 
X = df.drop(['price'],axis=1).to_numpy()
y = df.price.to_numpy().reshape(-1 , 1)

In [679]:
print(X.shape)
print(X[1])

(11471, 1609)
[0.097872948789835 0.0321062867779042 -0.3535339794590601 ... False False
 False]


In [680]:
print("X shape : ", X.shape)
print("y shape : ", y.shape)

X shape :  (11471, 1609)
y shape :  (11471, 1)


In [681]:
# df.corr()

In [682]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=42)

In [683]:
print("Shape of X_train: ", X_train.shape)
print("Shape of X_test: ", X_test.shape)
print("Shape of y_train: ", y_train.shape)
print("Shape of y_test: ", y_test.shape)

Shape of X_train:  (9176, 1609)
Shape of X_test:  (2295, 1609)
Shape of y_train:  (9176, 1)
Shape of y_test:  (2295, 1)


In [684]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train,y_train)
print(regressor.score(X_train, y_train))
print(regressor.score(X_test, y_test))

0.7185315659190843
-3.88663912800733e+20


In [685]:

from sklearn.linear_model import Lasso
regressor = Lasso(alpha=0.01)
regressor.fit(X_train,y_train)
print(regressor.score(X_train, y_train))
print(regressor.score(X_test, y_test))

/home/prng/Desktop/Arai-5/git/immo_eliza_regression/.venv/lib/python3.10/site-packages/sklearn/linear_model/_coordinate_descent.py:628: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.860e+14, tolerance: 3.456e+11
  model = cd_fast.enet_coordinate_descent(


0.7185302267869236
0.6579276695759652


In [686]:
y_pred = regressor.predict(X_test)
print(y_pred)

[147304.3790836  510034.16023138  90924.54589711 ... 318869.15704934
 425052.94702951 150266.24836672]


In [687]:
print(y)

[[170000.]
 [219000.]
 [219000.]
 ...
 [495000.]
 [499000.]
 [499000.]]


In [688]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(random_state=3)
regressor.fit(X_train, y_train)
print(regressor.score(X_train, y_train))
print(regressor.score(X_test, y_test))

/home/prng/Desktop/Arai-5/git/immo_eliza_regression/.venv/lib/python3.10/site-packages/sklearn/base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


0.968326022603833
0.8292143453006684


In [689]:
y_pred = regressor.predict(X_test)
print(y_pred)

[180370. 489970. 203578. ... 441140. 396840. 693820.]


In [690]:
print(y)

[[170000.]
 [219000.]
 [219000.]
 ...
 [495000.]
 [499000.]
 [499000.]]


In [691]:
df

postalCode     price   n_rooms  living_area  equipped_kitchen  \
0       -1.059352  170000.0 -0.569677    -0.795057               1.0   
1        0.097873  219000.0  0.032106    -0.353534               1.0   
2        1.675033  219000.0 -1.171460    -0.382969               1.0   
3        1.578865  245000.0 -1.171460    -0.883362               1.0   
4       -1.081792  330000.0 -0.569677    -0.603730               1.0   
...           ...       ...       ...          ...               ...   
11466    0.745406  494000.0  0.633889     0.095348               0.0   
11467   -0.950362  495000.0  0.633889     0.191011               0.0   
11468   -0.434258  495000.0  0.633889     0.610458               1.0   
11469   -0.953567  499000.0 -1.773243     1.162361               1.0   
11470   -0.815405  499000.0  1.235672     0.845937               0.0   

       furnished  fireplace  terrace  area_terrace  garden  ...  \
0            0.0        0.0      1.0     -0.523385     0.0  ...   
1            0.0        0.0      1.0      0.101605     1.0  ...   
2            0.0        0.0      0.0     -0.589173     1.0  ...   
3            0.0        0.0      1.0     -0.260231     0.0  ...   
4            0.0        0.0      1.0     -0.326020     0.0  ...   
...          ...        ...      ...           ...     ...  ...   
11466        0.0        0.0      1.0      0.726594     1.0  ...   
11467        0.0        0.0      1.0      0.002922     0.0  ...   
11468        0.0        0.0      1.0      0.068710     1.0  ...   
11469        0.0        0.0      0.0     -0.589173     0.0  ...   
11470        0.0        0.0      1.0      0.825277     1.0  ...   

       subtype_property_LOFT  subtype_property_MANOR_HOUSE  \
0                      False                         False   
1                      False                         False   
2                      False                         False   
3                      False                         False   
4                      False                         False   
...                      ...                           ...   
11466                  False                         False   
11467                  False                         False   
11468                  False                         False   
11469                  False                         False   
11470                  False                         False   

       subtype_property_MANSION  subtype_property_MIXED_USE_BUILDING  \
0                         False                                False   
1                         False                                False   
2                         False                                False   
3                         False                                False   
4                         False                                False   
...                         ...                                  ...   
11466                      True                                False   
11467                     False                                False   
11468                     False                                False   
11469                     False                                 True   
11470                     False                                False   

       subtype_property_OTHER_PROPERTY  subtype_property_PENTHOUSE  \
0                                False                       False   
1                                False                       False   
2                                False                       False   
3                                False                       False   
4                                False                       False   
...                                ...                         ...   
11466                            False                       False   
11467                            False                       False   
11468                            False                       False   
11469                      